apiVersion: v2
name: mongodb
description: MongoDB with Replica Set support
type: application
version: 0.1.0
appVersion: "7.0"
keywords:
  - mongodb
  - database
  - replicaset
home: https://www.mongodb.com/
sources:
  - https://github.com/mongodb/mongo
maintainers:
  - name: aadinnr
    email: aadinnr@example.com
