apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: demo-mongo-apps

resources:
  - deploy-mongodb.yml
  - deploy-mongoexp.yml
  # - svc.yml
  # - ingress.yml
  - cm.yml
  - secret.yml
