apiVersion: v1
kind: ConfigMap
metadata:
  name: kibana-config
  namespace: elastic-stack
data:
  kibana.yml: |
    server.name: kibana
    server.host: "0.0.0.0"
    elasticsearch.hosts: [ "http://elasticsearch.elastic-stack.svc.cluster.local:9200" ]
    xpack.security.enabled: false
    xpack.encryptedSavedObjects.encryptionKey: "something_at_least_32_characters_long"
    xpack.reporting.encryptionKey: "something_at_least_32_characters_long"
    xpack.security.encryptionKey: "something_at_least_32_characters_long"
    # Monitoring
    xpack.monitoring.ui.container.elasticsearch.enabled: true
    # Default app (removed invalid config)
    # Logging
    logging.appenders:
      console:
        type: console
        layout:
          type: json
    logging.loggers:
      - name: http.server.response
        appenders: [console]
        level: error
