apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: demo-app-staging
  namespace: argocd
  annotations:
    argocd-image-updater.argoproj.io/image-list: |
      frontend=aadinnr/demo_devops
      backend=aadinnr/demo_devops

    # Frontend
    argocd-image-updater.argoproj.io/frontend.allow-tags: regexp:^frontend-v[0-9]+\.[0-9]+\.[0-9]+$
    argocd-image-updater.argoproj.io/frontend.extractor: semver
    argocd-image-updater.argoproj.io/frontend.update-strategy: semver
    argocd-image-updater.argoproj.io/frontend.helm.image-name: frontend.image.repository
    argocd-image-updater.argoproj.io/frontend.helm.image-tag: frontend.image.tag

    # Backend
    argocd-image-updater.argoproj.io/backend.allow-tags: regexp:^backend-v[0-9]+\.[0-9]+\.[0-9]+$
    argocd-image-updater.argoproj.io/backend.extractor: semver
    argocd-image-updater.argoproj.io/backend.update-strategy: semver
    argocd-image-updater.argoproj.io/backend.helm.image-name: backend.image.repository
    argocd-image-updater.argoproj.io/backend.helm.image-tag: backend.image.tag

    # Write changes back to Git repo (so they persist in values.yaml)
    argocd-image-updater.argoproj.io/write-back-method: git
spec:
  project: demo-project
  source:
    repoURL: https://github.com/SeoulX/aadinnr_files.git
    targetRevision: main
    path: phase3/k8s/demo_devops/environments/staging
  destination:
    server: https://kubernetes.default.svc
    namespace: demo-apps
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
