apiVersion: v1
data:
  my-token: emVuMGh1YjpkY2tyX3BhdF82VDBoZlYxYmFmRWZ2NmpkN0M5QUxCZFhybjg=
kind: Secret
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","data":{"my-token":"emVuMGh1YjpkY2tyX3BhdF82VDBoZlYxYmFmRWZ2NmpkN0M5QUxCZFhybjg="},"kind":"Secret","metadata":{"annotations":{},"name":"dockerhub","namespace":"argocd"},"type":"Opaque"}
  creationTimestamp: "2023-12-22T15:04:09Z"
  name: dockerhub
  namespace: argocd
  resourceVersion: "3126956"
  uid: 9f1b151a-6a0f-403f-83c0-bd8b88c625fa
type: Opaque
