apiVersion: v1
kind: ConfigMap
metadata:
  name: demo-app-config
  namespace: demo-apps
data:
  AWS_REGION: ap-southeast-2
  DYNAMODB_TABLE_Main: InternsTable
  DYNAMODB_TABLE_Record: DailyTimeRecordsTable
  NEXT_PUBLIC_API_URL: demo-app-backend-svc
