apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-app-frontend-staging
  namespace: demo-apps
  labels:
    app: demo-app-frontend-staging
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demo-app-frontend-staging
  template:
    metadata:
      labels:
        app: demo-app-frontend-staging
    spec:
      containers:
        - name: demo-app
          image: aadinnr/demo_devops:frontend-v4.0.2
          ports:
            - containerPort: 3000
          env:
            - name: NEXT_PUBLIC_API_BASE_URL
              valueFrom:
                configMapKeyRef:
                  name: demo-app-config
                  key: NEXT_PUBLIC_API_BASE_URL
          volumeMounts:
          - name: config-vol
            mountPath: /etc/config
          - name: secret-vol
            mountPath: /etc/secret
      volumes:
      - name: config-vol
        configMap:
          name: demo-app-config
      - name: secret-vol
        secret:
          secretName: demo-app-secret
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-app-backend-staging
  namespace: demo-apps
  labels:
    app: demo-app-backend-staging
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demo-app-backend-staging
  template:
    metadata:
      labels:
        app: demo-app-backend-staging
    spec:
      containers:
        - name: demo-app
          image: aadinnr/demo_devops:backend-v4.0.2
          ports:
            - containerPort: 8000
          env:
            # From ConfigMap
            - name: AWS_REGION
              valueFrom:
                configMapKeyRef:
                  name: demo-app-config
                  key: AWS_REGION
            - name: DYNAMODB_TABLE_Main
              valueFrom:
                configMapKeyRef:
                  name: demo-app-config
                  key: DYNAMODB_TABLE_Main
            - name: DYNAMODB_TABLE_Record
              valueFrom:
                configMapKeyRef:
                  name: demo-app-config
                  key: DYNAMODB_TABLE_Record
            # From Secret
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: demo-app-secret
                  key: AWS_ACCESS_KEY_ID
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: demo-app-secret
                  key: AWS_SECRET_ACCESS_KEY
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: demo-app-secret
                  key: JWT_SECRET
