apiVersion: v1
kind: Service
metadata:
  name: demo-app-svc
  namespace: demo-apps
  labels:
    app: demo-app
spec:
  type: ClusterIP
  selector:
    app: demo-app-staging
  ports:
    - port: 80
      targetPort: 3000
