apiVersion: v1
kind: Pod
metadata:
  name: demo-pod
  namespace: demo-app
  labels:
    app: demo
spec:
  containers:
    - name: demo-container
      image: nginx:latest
      ports:
        - containerPort: 80
